services:
  api:
    build: .
    ports:
      - "3010:3000"
    depends_on:
      - db
    volumes:
      - .:/my_todo_rails
      - bundle:/usr/local/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3316:3306"
volumes:
  mysql_data:
  bundle:
