name: Run RSpec

on:
  push:
    branches: [ feature/41 ]
  pull_request:
    branches: [ feature/41 ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: my_todo_rails_test
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        make docker_build
        make db_create
        make db_migrate
      env:
        RAILS_ENV: test
    - name: RSpec
      env:
        RAILS_ENV: test
        # DATABASE_URL: mysql2://root:password@localhost:3306/my_todo_rails_test
      run: |
        make rspec
