name: Run RSpec

on:
  push:
    branches: [ feature/41 ]
  pull_request:
    branches: [ feature/41 ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Show ruby version
        run: ruby -v

      - name: Run lint
        run: bundle exec rubocop

  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          # MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: my_todo_rails_test
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
        bundler-cache: true

    - name: Build and test
      env:
        RAILS_ENV: test
        DATABASE_URL: mysql2://root:password@127.0.0.1:3306/my_todo_rails_test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        sudo /etc/init.d/mysql start
        bundle exec rails db:create
        bundle exec ridgepole -c config/database.yml -f db/schemas/Schemafile --apply
        bundle exec rspec
